export const Videos = [
  {
    id: "case-2",
    eyebrow: "CASE STUDIES",
    heading: "Hear directly from our customers",
    blurb: "Learn how Infrasity's deep technical content helped solve engineers' pain points and attract more prospects.",
    cta: { label: "See case studies", href: "/case-studies/case-study-series-a-cloud-developer-marketing" },

    headshotSrc: "/playbook/firefly.png",
    headshotAlt: "Eric Peters",
    companyLogoSrc: "/playbook/firefly-bg.png",
    companyLogoAlt: "Firefly.ai",
    quote: "Infrasity's unique ability to create deep, technical content that resonates with engineers has been valuable in helping us identify and address our customers pain points.",
    personName: "Idoo Neeman",
    personTitle: "Co-Founder and CEO, Firefly.ai",
    videoUrl: "https://youtube.com/shorts/AgCQ176pfRU",
  },
  {
    id: "case-1",
    eyebrow: "CASE STUDIES",
    heading: "Hear directly from our customers",
    blurb: "Learn how Infrasity turned our technical value into engaging content that boosts developer engagement.",
    cta: { label: "See case studies", href: "/case-studies" },

    headshotSrc: "/playbook/cycloid.png",
    headshotAlt: "Ben Hewison",
    companyLogoSrc: "/playbook/cycloid-bg.png",
    companyLogoAlt: "Cycloid",
    quote: "Infrasity's experience in platform engineering and DevOps gave us confidence that they could translate our technical value into engaging content and videos.",
    personName: "Ben Hewison",
    personTitle: "Content Marketing Manager, Cycloid",
    videoUrl: "https://youtu.be/19Nz5OxaTtc",
  },
  {
    id: "case-3",
    eyebrow: "CASE STUDIES",
    heading: "Hear directly from our customers",
    blurb: "Discover how Infrasity's technical content strategy drives developer adoption and growth.",
    cta: { label: "See case studies", href: "/case-studies" },

    headshotSrc: "/Testimon/joshTerraTeam-new.jpg",
    headshotAlt: "Josh",
    companyLogoSrc: "/trustedby/terrateam.png",
    companyLogoAlt: "Terrateam",
    quote: "Infrasity's dedication to understanding our audience's needs was evident in their research on what Engineers look for in content. By focusing on teachings rather than selling, their content has empowered our users with new skills and solutions. Their work has significantly boosted our web and blog traffic, and we highly recommend their expertise.",
    personName: "Josh",
    personTitle: "Co-Founder, Terrateam",
    videoUrl: "https://youtube.com/shorts/zq4ga3BbbGU?si=1NTay8-ss830v9fb",
  }
];
