
export const clientLogo = [
  "brevo.png",
  "cardinal.webp",
  "inframail.webp",
  "ollm.svg",
  "qualifier.webp",
  "respond.png",
  "teleport.webp",
  "mocha.png",
  "aviator.png",
  "firstock-logo.webp",
  "dhiwise.svg",
  "amnic.png",
  "oso.png",
  "ox-sec.svg",
  "cedana.png",
  "cerbos.png",
  "codegiant-infra-1.png",
  "cycloid.png",
  "daytona-removebg-preview-e1721477918328.png",
  "DevZero.png",
  "env0-infra-1.png",
  "firefly.png",
  "Group-14967.png",
  "images-removebg-preview.png",
  "images__2_-removebg-preview.png",
  "kapstan.png",
  "kubiya.png",
  "logo-landscape-removebg-preview.png",
  "lovable-logo.png",
  "Mask-group.png",
  "scalr.png",
  "stackOne.svg",
  "TravisCI-Full-Color.png",
  "terrateam.png",
  "vapi.png",
  "qodo-logo.svg",
];

export const serviceClientLogo = [
  "brevo.png",
  "cardinal.png",
  "inframail.png",
  "ollm.png",
  "qualifier.png",
  "respond.png",
  "teleport.png",
  "aviator.png",
  "mocha.png",
  "cedana.png",
  "dhiwise.png",
  "amnic.png",
  "oso.png",
  "ox-sec.svg",
  "mvp-grow.png",
  "cerbos.png",
  "qodo-logo.png",
  "Codegiant.png",
  "Scalekit-logo.png",
  "scalr.png",
  "daytona.png",
  "stackOne.png",
  "DevZero.png",
  "terrateam.png",
  "env0-infra-1.png",
  "tracetest.png",
  "firefly.png",
  "TravisCI-Full-Color.png",
  "firstock-logo.png",
  "vapi-logo.png",
  "kapstan.png",
  "Zenml.png",
  "Kubiya.png",
  "lovable-logo.png",
  "Meteor-ops.png",
];

export const clientPaddingMap = {
  "cardinal.webp": "p-12",
  "dhiwise.svg": "p-6",
  "qodo-logo.svg": "p-8",
  "stackOne.svg": "p-4",
  "mocha.png": "p-8",
  "oso.png": "p-12",
  "ox-sec.svg": "p-8",
  "aviator.png": "p-3",
  "firstock-logo.webp": "p-5",
  "amnic.png": "p-6",
  "cedana.png": "p-5",
  "cerbos.png": "p-4",
  "codegiant-infra-1.png": "p-3",
  "cycloid.png": "p-7",
  "daytona-removebg-preview-e1721477918328.png": "p-5",
  "DevZero.png": "p-4",
  "env0-infra-1.png": "p-6",
  "firefly.png": "p-5",
  "Group-14967.png": "p-4",
  "images-removebg-preview.png": "p-6",
  "images__2_-removebg-preview.png": "p-6",
  "kapstan.png": "p-4",
  "kubiya.png": "p-5",
  "logo-landscape-removebg-preview.png": "p-2",
  "lovable-logo.png": "p-4",
  "Mask-group.png": "p-5",
  "scalr.png": "p-4",
  "TravisCI-Full-Color.png": "p-5",
  "terrateam.png": "p-4",
  "vapi.png": "p-5",
};

export const clientWhiteLogo = [
  "brevo.png",
  "cycloid.png",
  "devzero.png",
  "dhiwise.png",
  "firefly.png",
  "inframail.png",
  "kubiya.png",
  "Mocha.png",
  "mvpgrow.png",
  "ollm.png",
  "qualifier.png",
  "respond.png",
  "scalekit.png",
  "scalr.png",  
  "teleport.png"
];
export const clientWhiteStyle = {
  "brevo.png":"object-cover",
  "cycloid.png":"object-contain",
  "devzero.png":"object-contain",
  "dhiwise.png":"object-cover",
  "firefly.png":"object-contain",
  "inframail.png":"object-cover",
  "kubiya.png":"object-contain",
  "Mocha.png":"object-contain",
  "mvpgrow.png":"object-contain",
  "ollm.png":"object-cover",
  "qualifier.png":"object-cover",
  "respond.png":"object-cover",
  "scalekit.png":"object-contain",
  "scalr.png":"object-contain",  
  "teleport.png":"object-cover"
};
